manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com
  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: v3.7.0
      import: true
  self:
    path: app
